apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  template:
    spec:
      serviceAccountName: kaniko-builder
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=Dockerfile"
            - "--context=git://github.com/tinotenda-alfaneti/atarnet-homelab.git"
            - "--destination=tinotendaalfaneti/atarnet-homelab:latest"
            - "--verbosity=info"
            - "--cleanup"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      volumes:
        - name: docker-config
          projected:
            sources:
              - secret:
                  name: dockerhub-creds
                  items:
                    - key: .dockerconfigjson
                      path: config.json
